### ISSUE TITLE
"com.example.webserver.memory.max" is maybe a bad example

### ISSUE THREAD

**Issue by larsks** [projectatomic/ContainerApplicationGenericLabels#15] opened 2015-05-16 02:07 UTC
The spec includes the following example:

| Sample Name | Sample Description |
| --- | --- |
| `com.example.webserver.memory.max` | Maximum memory setting for "example.com" organization's webserver |
| `com.example.webserver.memory.min` | Minimum memory setting for "example.com" organization's webserver |

I am not sure if this is a bad example or if I don't understand the idea behind it.  If I were building a webserver image, I would not apply a label called "something.webserver.memory.max".  I would just apply a "memory.max" label, and it would be for the webserver because that is the image to which it is applied.  There wouldn't be any need to encode this fact in the name of the label.

If the idea here is that an organization might want to namespace labels because they want to avoid conflicts with labels used at other organizations that makes sense, but using `com.example.memory.max` and `com.example.memory.min` might better illustrate the idea (because here namespacing is used exclusively as an organizational differentiator).

**Comment by rhatdan** [comment] 2015-05-16 09:56
I am thinking we might just want to remove this section.  Or clean it up as you suggest.

**Comment by philips** [comment] 2015-05-17 00:35
Dupe of #7 and removed by #16

**Comment by rhatdan** [comment] 2015-05-18 12:59
Removed section,  Not appropriate

**Closed as completed by rhatdan** 2015-05-18 12:59 UTC
